name: test

on:
  push:
    branches: [feature]
    paths: .github/workflows/test.yaml
  pull_request:
    branches: [feature]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-deploy-aks:
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: cluster-1
      RESOURCE_GROUP: cluster-1
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az account show
          az storage -h

    - name: Set up kubelogin for non-interactive login
      uses: azure/use-kubelogin@v1
      with:
        kubelogin-version: 'v0.0.25'    

    - name: Get K8s context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }}
        admin: 'false'
        use-kubelogin: 'true'   

    - name: Deploys application
      uses: Azure/k8s-deploy@v4
      with:
       resource-group: ${{ env.RESOURCE_GROUP }}
       action: deploy
       # private-cluster: true
       namespace: demo
       manifests: |
         kubectl apply -f demo/test.yaml

    
